image: python:3.7-stretch

cache:
    paths:
      - .venv
    untracked: true

stages:
  - tests
  - upload

variables:
  CACHE_NAME: $CI_PIPELINE_ID
  PACKAGE_NAME: marshmallow-jam

tests_python_3.7:
  image: python:3.7-stretch
  stage: tests
  script:
    - make pip_install
    - make ci_test
  artifacts:
    paths:
      - .reports
    expire_in: 1 week

.pypi: &upload_base
  stage: upload
  script:
    - pip install twine
    - python setup.py sdist
    - twine upload dist/*
  when: on_success
  environment:
    name: pypi.org
    url: https://pypi.org/$PACKAGE_NAME

upload:development:
  <<: *upload_base
  variables:
    DEV_VERSION: $CI_PIPELINE_ID
  when: manual

upload:production:
  <<: *upload_base
  only:
    - tags